# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

url: https://kinalmehta.github.io
baseurl: /mm_theme

title: Kinal
email: "kgm1995@gmail.com"
description: >- # this means to ignore newlines until "baseurl:"
  Hi, I am Kinal Mehta. I am a research student at IIITH interested in "Learning in autonomous agents"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
twitter_username: kinal_mehta
github_username: kinalmehta
minimal_mistakes_skin: dark # air, dark, neon, default
search: true

# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  # math_engine: mathjax

remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 9 # amount of posts to show
paginate_path: /page:num/
timezone: Asia/Kolkata # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Kinal Mehta"
  avatar : "/assets/images/kinal_profile.jpg"
  bio    : "Learning Algorithms Researcher"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://kinalmehta.github.io"
    - label: "Email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:kgm1995@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kinalmehta"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kinalmehta"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/kinal_mehta"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=IJIXl8oAAAAJ"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/kinalmehta"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=IJIXl8oAAAAJ"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kinalmehta"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/kinal_mehta"

# Collections
collections:
  classnotes:
    output: true
    permalink: /:collection/:path/
    author_profile: false


defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true
  # _classnotes
  - scope:
      path: ""
      type: classnotes
    values:
      layout: single
      author_profile: false
      read_time: true
      share: true
      comments: true
      related: true
      sidebar:
        nav: classnotes

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
